version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    depends_on:
      - app
    container_name: nginx_app
    
  app:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    command: bash -c "if [ ! -f '.env' ]; then cp .env.example .env; fi && if [ ! -d 'vendor' ]; then composer install && php artisan key:generate; fi && php-fpm"
    container_name: app

  node:
    image: node:20.11.1
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: bash -c "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev"
    depends_on:
      - app
    container_name: node_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_postapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db_app
